tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: FIVETRANSECTEST
      schema: sampleschema_stg_workday
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: FIVETRANSECTEST
      schema: sampleschema_stg_workday
